/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package week_01;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author LOAN
 */
public class frm_Playfair extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frm_Playfair.class.getName());

    /**
     * Creates new form frm_Playfair
     */
    private PlayfairCipher playFairCipher;
    public frm_Playfair() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPlaintext = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtKey = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCiphertext = new javax.swing.JTextArea();
        btEncrypt = new javax.swing.JButton();
        btDecrypt = new javax.swing.JButton();
        btOpenCiphertextFile = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtKeyMatrix = new javax.swing.JTextArea();
        btGenerateKeyMatrix = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Playfair Cipher Demo");

        txtPlaintext.setColumns(20);
        txtPlaintext.setRows(5);
        jScrollPane1.setViewportView(txtPlaintext);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Plaintext:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Key:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Ciphertext:");

        txtCiphertext.setColumns(20);
        txtCiphertext.setRows(5);
        jScrollPane2.setViewportView(txtCiphertext);

        btEncrypt.setText("Encrypt");
        btEncrypt.addActionListener(this::btEncryptActionPerformed);

        btDecrypt.setText("Decrypt");
        btDecrypt.addActionListener(this::btDecryptActionPerformed);

        btOpenCiphertextFile.setText("Open Ciphertext File");
        btOpenCiphertextFile.addActionListener(this::btOpenCiphertextFileActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Key Matrix:");

        txtKeyMatrix.setColumns(20);
        txtKeyMatrix.setRows(5);
        jScrollPane3.setViewportView(txtKeyMatrix);

        btGenerateKeyMatrix.setText("Generate Key Matrix");
        btGenerateKeyMatrix.addActionListener(this::btGenerateKeyMatrixActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(jLabel2))
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtKey)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel5)
                            .addGap(12, 12, 12)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btGenerateKeyMatrix)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btEncrypt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btDecrypt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btOpenCiphertextFile)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEncrypt)
                    .addComponent(btDecrypt)
                    .addComponent(btOpenCiphertextFile)
                    .addComponent(btGenerateKeyMatrix))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEncryptActionPerformed
        // TODO add your handling code here:
        String plaintext = txtPlaintext.getText();
        String key = txtKey.getText();
        
        if(!plaintext.isEmpty() && !key.isEmpty()){
            playFairCipher = new PlayfairCipher(key);
            String ciphertext = playFairCipher.encrypt(plaintext);
            JOptionPane.showMessageDialog(this, "Encrypted successfully.");
            txtCiphertext.setText(ciphertext);
            saveToFile(ciphertext);
        } else
            JOptionPane.showMessageDialog(this, "Please enter plaintext and key.");
    }//GEN-LAST:event_btEncryptActionPerformed

    private void btDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDecryptActionPerformed
        // TODO add your handling code here:
        String ciphertext = txtCiphertext.getText();
        String key = txtKey.getText();
        
        if(!ciphertext.isEmpty() && !key.isEmpty()){
            playFairCipher = new PlayfairCipher(key);
            String plaintext = playFairCipher.decrypt(ciphertext);
            JOptionPane.showMessageDialog(this, "Decrypted successfully.");
            txtPlaintext.setText(plaintext);
        } else
            JOptionPane.showMessageDialog(this, "Please enter plaintext and key.");
    }//GEN-LAST:event_btDecryptActionPerformed

    private void btOpenCiphertextFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpenCiphertextFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Text Files", "txt"));

        int userSelection = fileChooser.showOpenDialog(this);
        if(userSelection == JFileChooser.APPROVE_OPTION){
            try(BufferedReader bufferedReader = new BufferedReader(new FileReader(fileChooser.getSelectedFile()))){
                JOptionPane.showMessageDialog(this, "File opened successfully.");
                txtCiphertext.read(bufferedReader, null);
            } catch(IOException e){
                JOptionPane.showMessageDialog(this, "Error opening File: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btOpenCiphertextFileActionPerformed

    private void saveToFile(String content){
       JFileChooser fileChooser = new JFileChooser();
       FileNameExtensionFilter filter = new FileNameExtensionFilter("Text Files", "txt");
       fileChooser.setFileFilter(filter);
       int userSelection = fileChooser.showSaveDialog(this);
       if(userSelection == JFileChooser.APPROVE_OPTION){
           try(java.io.FileWriter fileWrite = new java.io.FileWriter(fileChooser.getSelectedFile() + ".txt")){
               JOptionPane.showMessageDialog(this, "File save successfully.");
               fileWrite.write(content);
           } catch(IOException e){
               JOptionPane.showMessageDialog(this, "Error saving file; " + e.getMessage());
           }
       }
    }
    
    private void btGenerateKeyMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGenerateKeyMatrixActionPerformed
        // TODO add your handling code here:
        String key = txtKey.getText();
        if(!key.isEmpty()){
            playFairCipher = new PlayfairCipher(key);
            String keyMatrixString = playFairCipher.getKeyMatrixAsString();
            txtKeyMatrix.setText(keyMatrixString);
        } else
            JOptionPane.showMessageDialog(this, "Please enter key to generate key matrix.");
    }//GEN-LAST:event_btGenerateKeyMatrixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frm_Playfair().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDecrypt;
    private javax.swing.JButton btEncrypt;
    private javax.swing.JButton btGenerateKeyMatrix;
    private javax.swing.JButton btOpenCiphertextFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtCiphertext;
    private javax.swing.JTextField txtKey;
    private javax.swing.JTextArea txtKeyMatrix;
    private javax.swing.JTextArea txtPlaintext;
    // End of variables declaration//GEN-END:variables
}
