/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package week_04;

import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.nio.file.Paths;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.MessageDigest;
import java.security.PublicKey;
import java.security.spec.X509EncodedKeySpec;
import java.util.Arrays;
import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.KeyAgreement;
import javax.crypto.SecretKey;
import javax.crypto.interfaces.DHPublicKey;
import javax.crypto.spec.DHParameterSpec;
import javax.crypto.spec.SecretKeySpec;

/**
 *
 * @author Administrator
 */
public class frm_Bob extends javax.swing.JFrame {

    /**
     * Creates new form frm_Bob
     */
    public frm_Bob() {
        initComponents();
    }
    
    KeyAgreement bobKeyAgree;
    PublicKey alicePubKey;
    SecretKey bobDesKey;
    Cipher bobCipher;

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAliceKey = new javax.swing.JTextField();
        btBobKeyGenerate = new javax.swing.JButton();
        btAliceKeyDisplay = new javax.swing.JButton();
        txtBobKey = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSharedSecret = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEncryptSharedSecret = new javax.swing.JTextField();
        btEncryptSecretKey = new javax.swing.JButton();
        btRunEDForm = new javax.swing.JButton();
        btMakeSecretKey = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Bob Form (D-H)");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Alice's Key:");

        btBobKeyGenerate.setText("Bob's Key Generate");
        btBobKeyGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBobKeyGenerateActionPerformed(evt);
            }
        });

        btAliceKeyDisplay.setText("Alice's Key Display");
        btAliceKeyDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAliceKeyDisplayActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Bob's Key:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Shared Secret:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Encrypt Shared Secret:");

        btEncryptSecretKey.setText("Encrypt Secret Key");
        btEncryptSecretKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEncryptSecretKeyActionPerformed(evt);
            }
        });

        btRunEDForm.setText("Run Encrypt/Decrypt Form");
        btRunEDForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRunEDFormActionPerformed(evt);
            }
        });

        btMakeSecretKey.setText("Make Secret Key");
        btMakeSecretKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMakeSecretKeyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSharedSecret, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtAliceKey, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBobKey, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btRunEDForm)
                                    .addComponent(txtEncryptSharedSecret, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btMakeSecretKey, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btBobKeyGenerate)
                            .addComponent(btAliceKeyDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btEncryptSecretKey, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBobKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btBobKeyGenerate)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAliceKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAliceKeyDisplay))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSharedSecret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMakeSecretKey))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEncryptSharedSecret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEncryptSecretKey))
                .addGap(18, 18, 18)
                .addComponent(btRunEDForm)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBobKeyGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBobKeyGenerateActionPerformed
        // TODO add your handling code here:
        try {
            boolean read = false;
            java.nio.file.Path dirPath = Paths.get("src/week_04");
            if (!java.nio.file.Files.exists(dirPath))
                java.nio.file.Files.createDirectories(dirPath);
            
            while (!read) {
                try (FileInputStream fis = new FileInputStream(dirPath.resolve("A.pub").toFile())) {
                    read = true;
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
            byte[] alicePubKeyEnc;
            try (FileInputStream fis = new FileInputStream(dirPath.resolve("A.pub"). toFile())) {
                alicePubKeyEnc = new byte[fis.available()];
                fis.read(alicePubKeyEnc);
            }
            KeyFactory bobKeyFac = KeyFactory.getInstance("DH");
            X509EncodedKeySpec x509KeySpec = new X509EncodedKeySpec(alicePubKeyEnc);
            alicePubKey = bobKeyFac.generatePublic(x509KeySpec);
            DHParameterSpec dhParamSpec = ((DHPublicKey) alicePubKey).getParams();
            KeyPairGenerator bobKpaiGen = KeyPairGenerator.getInstance("DH");
            bobKpaiGen.initialize(dhParamSpec);
            KeyPair bobKpair = bobKpaiGen.generateKeyPair();
            bobKeyAgree = KeyAgreement.getInstance("DH");
            bobKeyAgree.init(bobKpair.getPrivate());
            byte[] bobPubKeyEnc = bobKpair.getPublic().getEncoded();
            try (FileOutputStream fos = new FileOutputStream(dirPath.resolve("B.pub").toFile())) {
                fos.write(bobPubKeyEnc);
            }
            txtBobKey.setText(java.util.Base64.getEncoder().encodeToString(bobPubKeyEnc));
        } catch (Exception ex) {
            ex.printStackTrace();
        }  
    }//GEN-LAST:event_btBobKeyGenerateActionPerformed

    private void btAliceKeyDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAliceKeyDisplayActionPerformed
        // TODO add your handling code here:
        try {
            System.out.println("yoyoyoyoyoy");
            byte[] bkeyP;
            try (FileInputStream fis = new FileInputStream(Paths.get("src/week_04/A.pub").toFile())) {
                bkeyP = new byte[fis.available()];
                fis.read(bkeyP);
            }
            System.out.println("yoyoyoyoyoy");
            txtAliceKey.setText(bkeyP.toString());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btAliceKeyDisplayActionPerformed

    private void btEncryptSecretKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEncryptSecretKeyActionPerformed
        // TODO add your handling code here:
        try {
            bobKeyAgree.doPhase(alicePubKey, true);
            byte[] sharedSecret = bobKeyAgree.generateSecret();
            txtEncryptSharedSecret.setText(CryptoUtil.toHexString(sharedSecret));
            MessageDigest sha256 = MessageDigest.getInstance("SHA-256");
            byte[] deskeyBytes = Arrays.copyOf(sha256.digest(sharedSecret), 8);
            SecretKeySpec desKeySpec = new SecretKeySpec(deskeyBytes,"DES");
            txtEncryptSharedSecret.setText(Base64.getEncoder().encodeToString(desKeySpec.getEncoded()));
            String fileName = "src/week_04/B.txt";
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(fileName))) {
                bw.write(Base64.getEncoder().encodeToString(desKeySpec.getEncoded()));
            }
        } catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btEncryptSecretKeyActionPerformed

    private void btRunEDFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRunEDFormActionPerformed
        // TODO add your handling code here:
        frm_DESCS des = new frm_DESCS();
        des.setVisible(true);
    }//GEN-LAST:event_btRunEDFormActionPerformed

    private void btMakeSecretKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMakeSecretKeyActionPerformed
        // TODO add your handling code here:
        try {
            bobKeyAgree.doPhase(alicePubKey, true);
            byte[] bobSharedSecret = bobKeyAgree.generateSecret();
            txtSharedSecret.setText(CryptoUtil.toHexString(bobSharedSecret));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btMakeSecretKeyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Bob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAliceKeyDisplay;
    private javax.swing.JButton btBobKeyGenerate;
    private javax.swing.JButton btEncryptSecretKey;
    private javax.swing.JButton btMakeSecretKey;
    private javax.swing.JButton btRunEDForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAliceKey;
    private javax.swing.JTextField txtBobKey;
    private javax.swing.JTextField txtEncryptSharedSecret;
    private javax.swing.JTextField txtSharedSecret;
    // End of variables declaration//GEN-END:variables
}
