/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package week_04;

import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.lang.reflect.Array;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.AlgorithmParameterGenerator;
import java.security.AlgorithmParameters;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.PublicKey;
import java.security.spec.X509EncodedKeySpec;
import java.util.Arrays;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.KeyAgreement;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import week_02.frm_DES;

/**
 *
 * @author Administrator
 */
public class frm_Alice extends javax.swing.JFrame {

    /**
     * Creates new form frm_Alice
     */
    public frm_Alice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSharedSecret = new javax.swing.JTextField();
        txtEncryptSharedSecret = new javax.swing.JTextField();
        txtBobKey = new javax.swing.JTextField();
        txtAliceKey = new javax.swing.JTextField();
        btRunEDForm = new javax.swing.JButton();
        btAliceKeyGenerate = new javax.swing.JButton();
        btBobKeyDisplay = new javax.swing.JButton();
        btMakeSecretKey = new javax.swing.JButton();
        btEncryptSecretKey = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Alice Form (D-H)");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Alice's Key:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Bob's Key:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Shared Secret:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Encrypt Shared Secret:");

        btRunEDForm.setText("Run Encrypt/Decrypt Form");
        btRunEDForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRunEDFormActionPerformed(evt);
            }
        });

        btAliceKeyGenerate.setText("Alice's Key Generate");
        btAliceKeyGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAliceKeyGenerateActionPerformed(evt);
            }
        });

        btBobKeyDisplay.setText("Bob's Key Display");
        btBobKeyDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBobKeyDisplayActionPerformed(evt);
            }
        });

        btMakeSecretKey.setText("Make Secret Key");
        btMakeSecretKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMakeSecretKeyActionPerformed(evt);
            }
        });

        btEncryptSecretKey.setText("Encrypt Secret Key");
        btEncryptSecretKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEncryptSecretKeyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(267, 267, 267))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addComponent(txtEncryptSharedSecret, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btEncryptSecretKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(102, 102, 102))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(108, 108, 108)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAliceKey, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btAliceKeyGenerate))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBobKey, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btBobKeyDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btRunEDForm)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSharedSecret, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btMakeSecretKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAliceKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAliceKeyGenerate))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBobKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBobKeyDisplay))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSharedSecret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMakeSecretKey))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btEncryptSecretKey)
                    .addComponent(txtEncryptSharedSecret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btRunEDForm)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    KeyAgreement aliceKeyAgree;
    PublicKey bobPubKey;
    SecretKey aliceDesKey;
    Cipher aliceCipher;
    
    private void btAliceKeyGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAliceKeyGenerateActionPerformed
        // TODO add your handling code here:
        
        try {
            AlgorithmParameterGenerator paramGen;
            paramGen = AlgorithmParameterGenerator.getInstance("DH");
            paramGen.init(512);
            AlgorithmParameters params = paramGen.generateParameters();
            DHParameterSpec dhSkipParamSpec = (DHParameterSpec) params.getParameterSpec(DHParameterSpec.class);
            System.out.println("Generating a DH KeyPair...");
            KeyPairGenerator aliceKPairGen = KeyPairGenerator.getInstance("DH");
            aliceKPairGen.initialize(dhSkipParamSpec);
            KeyPair aliceKPair = aliceKPairGen.generateKeyPair();
            System.out.println("Initializing the KeyAgreement Engine with DH private key");
            aliceKeyAgree = KeyAgreement.getInstance("DH");
            aliceKeyAgree.init(aliceKPair.getPrivate());
            byte[] alicePubKeyEnc = aliceKPair.getPublic().getEncoded();
            java.nio.file.Path dirPath = Paths.get("src/week_04");
            if (java.nio.file.Files.exists(dirPath))
                java.nio.file.Files.createDirectories(dirPath);
            try (FileOutputStream fos = new FileOutputStream(dirPath.resolve("A.pub").toFile())) {
                fos.write(alicePubKeyEnc);
            }
            txtAliceKey.setText(java.util.Base64.getEncoder().encodeToString(alicePubKeyEnc));           
        } catch (Exception ex) {
            ex.printStackTrace();
        }  
    }//GEN-LAST:event_btAliceKeyGenerateActionPerformed

    private void btBobKeyDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBobKeyDisplayActionPerformed
        // TODO add your handling code here:
        try {
            byte[] bkeyP;
            try (FileInputStream fis = new FileInputStream(Paths.get("src/week_04/B.pub").toFile())) {
                bkeyP = new byte[fis.available()];
                fis.read(bkeyP);
            }
            txtBobKey.setText(bkeyP.toString());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btBobKeyDisplayActionPerformed

    private void btMakeSecretKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMakeSecretKeyActionPerformed
        // TODO add your handling code here:
        try {
            byte[] bobPublicKeyEnc;
            try (FileInputStream fis = new FileInputStream(Paths.get("src/week_04/B.pub").toFile())) {
                bobPublicKeyEnc = new byte[fis.available()];
                fis.read(bobPublicKeyEnc);
            }
            KeyFactory aliceKeyFac = KeyFactory.getInstance("DH");
            X509EncodedKeySpec x509KeySpec = new X509EncodedKeySpec(bobPublicKeyEnc);
            bobPubKey = aliceKeyFac.generatePublic(x509KeySpec);
            System.out.println("Excuting PHASE1 of key agreement...");
            aliceKeyAgree.doPhase(bobPubKey, true);
            byte[] aliceSharedSecret = aliceKeyAgree.generateSecret();
            
            System.out.println("Khoa chung: secret (DEBUG ONLY):" + CryptoUtil.toHexString(aliceSharedSecret));
            txtSharedSecret.setText(CryptoUtil.toHexString(aliceSharedSecret));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btMakeSecretKeyActionPerformed

    private void btEncryptSecretKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEncryptSecretKeyActionPerformed
        // TODO add your handling code here:
        try {
            aliceKeyAgree.doPhase(bobPubKey, true);
            byte[] sharedSecret = aliceKeyAgree.generateSecret();
            txtEncryptSharedSecret.setText(CryptoUtil.toHexString(sharedSecret));
            MessageDigest sha256 = MessageDigest.getInstance("SHA-256");
            byte[] deskeyBytes = Arrays.copyOf(sha256.digest(sharedSecret), 8);
            SecretKeySpec desKeySpec = new SecretKeySpec(deskeyBytes,"DES");
            txtEncryptSharedSecret.setText(Base64.getEncoder().encodeToString(desKeySpec.getEncoded()));
            String fileName = "src/week_04/A.txt";
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(fileName))) {
                bw.write(Base64.getEncoder().encodeToString(desKeySpec.getEncoded()));
            }
        } catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btEncryptSecretKeyActionPerformed

    private void btRunEDFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRunEDFormActionPerformed
        // TODO add your handling code here:
        frm_DESCS des = new frm_DESCS();
        des.setVisible(true);
    }//GEN-LAST:event_btRunEDFormActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Alice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAliceKeyGenerate;
    private javax.swing.JButton btBobKeyDisplay;
    private javax.swing.JButton btEncryptSecretKey;
    private javax.swing.JButton btMakeSecretKey;
    private javax.swing.JButton btRunEDForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAliceKey;
    private javax.swing.JTextField txtBobKey;
    private javax.swing.JTextField txtEncryptSharedSecret;
    private javax.swing.JTextField txtSharedSecret;
    // End of variables declaration//GEN-END:variables
}
