/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package week_03;

import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author khang
 */
public class frm_RSA_AES extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frm_RSA_AES.class.getName());
    private RSA_AES_Cipher rsaCipher;
    /**
     * Creates new form frm_RSA_AES
     */
    public frm_RSA_AES() {
        initComponents();
        try {
            rsaCipher = new RSA_AES_Cipher();
        } catch(Exception ex) {
            Logger.getLogger(frm_RSA_AES.class.getName()).log(Level.SEVERE, null, ex);
                    
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPlaintext = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPublicKey = new javax.swing.JTextField();
        txtPrivateKey = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCiphertext = new javax.swing.JTextArea();
        btEncrypt = new javax.swing.JButton();
        btDecrypt = new javax.swing.JButton();
        btGenerateKey = new javax.swing.JButton();
        btLoadKey = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Plaintext:");

        txtPlaintext.setColumns(20);
        txtPlaintext.setRows(5);
        jScrollPane1.setViewportView(txtPlaintext);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("RSA-AES Cipher Demo");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Public Key:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Ciphertext:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Private Key:");

        txtCiphertext.setColumns(20);
        txtCiphertext.setRows(5);
        jScrollPane2.setViewportView(txtCiphertext);

        btEncrypt.setText("Encrypt");
        btEncrypt.addActionListener(this::btEncryptActionPerformed);

        btDecrypt.setText("Decrypt");
        btDecrypt.addActionListener(this::btDecryptActionPerformed);

        btGenerateKey.setText("Generate Keys");
        btGenerateKey.addActionListener(this::btGenerateKeyActionPerformed);

        btLoadKey.setText("Load Key");
        btLoadKey.addActionListener(this::btLoadKeyActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btGenerateKey)
                                .addGap(18, 18, 18)
                                .addComponent(btLoadKey)
                                .addGap(18, 18, 18)
                                .addComponent(btEncrypt)
                                .addGap(18, 18, 18)
                                .addComponent(btDecrypt)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPublicKey, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrivateKey, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(20, 20, 20))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel1)
                                .addContainerGap(254, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPublicKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrivateKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGenerateKey)
                    .addComponent(btLoadKey)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btEncrypt)
                        .addComponent(btDecrypt)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEncryptActionPerformed
        // TODO add your handling code here:
        try {
            String plaintext = txtPlaintext.getText();
            byte[] encryptedBytes = rsaCipher.encrypt(plaintext);
            
            String encryptedText = new String(encryptedBytes, StandardCharsets.ISO_8859_1);
            txtCiphertext.setText(encryptedText);
        } catch (IllegalBlockSizeException | BadPaddingException ex){
            Logger.getLogger(frm_RSA_AES.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error encrypting: " + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex){
            Logger.getLogger(frm_RSA_AES.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error Encrypting: " + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btEncryptActionPerformed

    private void btDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDecryptActionPerformed
        // TODO add your handling code here:
        try {
            byte[] combined = txtCiphertext.getText().getBytes(StandardCharsets.ISO_8859_1);
            String decryptedText = rsaCipher.decrypt(combined);

            txtPlaintext.setText(decryptedText);
        } catch (IllegalBlockSizeException | BadPaddingException ex){
            Logger.getLogger(frm_RSA_AES.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error Decrypting: " + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(frm_RSA_AES.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error Decrypting: " + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btDecryptActionPerformed

    private void btGenerateKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGenerateKeyActionPerformed
        // TODO add your handling code here:
        try {
            rsaCipher = new RSA_AES_Cipher();
            txtPublicKey.setText(rsaCipher.getPublicKey().toString());
            txtPrivateKey.setText(rsaCipher.getPrivateKey().toString());
            
            JFileChooser publicKeyChooser = new JFileChooser();
            publicKeyChooser.setDialogTitle("Sava Public Key File");
            int publicKeyChooserResult = publicKeyChooser.showSaveDialog(this);
            if (publicKeyChooserResult == JFileChooser.APPROVE_OPTION){
                File publicKeyFile = publicKeyChooser.getSelectedFile();
                try (FileWriter writer = new FileWriter(publicKeyFile.getAbsolutePath())){
                    writer.write(rsaCipher.getPublicKey().toString());
                    JOptionPane.showMessageDialog(this, "Public Key saved to file successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                } catch(IOException ex){
                    JOptionPane.showMessageDialog(this, "Error saving Public Key file.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            
            JFileChooser privateKeyChooser = new JFileChooser();
            privateKeyChooser.setDialogTitle("Sava Private Key File");
            int privateKeyChooserResult = privateKeyChooser.showSaveDialog(this);
            if (privateKeyChooserResult == JFileChooser.APPROVE_OPTION){
                File privateKeyFile = privateKeyChooser.getSelectedFile();
                try (FileWriter writer = new FileWriter(privateKeyFile.getAbsolutePath())){
                    writer.write(rsaCipher.getPrivateKey().toString());
                    JOptionPane.showMessageDialog(this, "Private Key saved to file successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                } catch(IOException ex){
                    JOptionPane.showMessageDialog(this, "Error saving Private Key file.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(frm_RSA_AES.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error generatting RSA key pair: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btGenerateKeyActionPerformed

    private void btLoadKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoadKeyActionPerformed
        // TODO add your handling code here:
        try{
            JFileChooser publicKeyChooser = new JFileChooser();
            publicKeyChooser.setDialogTitle("Load Public Key File");
            int publicKeyChooserResult = publicKeyChooser.showOpenDialog(this);
            if (publicKeyChooserResult == JFileChooser.APPROVE_OPTION){
                File publicKeyFile = publicKeyChooser.getSelectedFile();
                String publicKeyContent = readFile(publicKeyFile);
                txtPublicKey.setText(publicKeyContent);
            }
            
            JFileChooser privateKeyChooser = new JFileChooser();
            privateKeyChooser.setDialogTitle("Load Private Key File");
            int privateKeyChooserResult = privateKeyChooser.showOpenDialog(this);
            if (privateKeyChooserResult == JFileChooser.APPROVE_OPTION){
                File privateKeyFile = privateKeyChooser.getSelectedFile();
                String privateKeyContent = readFile(privateKeyFile);
                txtPrivateKey.setText(privateKeyContent);
            }
        } catch (HeadlessException | IOException ex) {
            Logger.getLogger(frm_RSA_AES.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error loading key: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btLoadKeyActionPerformed
    
    private String readFile(File file) throws IOException {
        StringBuilder contentBuilder = new StringBuilder();
        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = br.readLine()) != null)
                contentBuilder.append(line).append("\n");
        }
        return contentBuilder.toString();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frm_RSA_AES().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDecrypt;
    private javax.swing.JButton btEncrypt;
    private javax.swing.JButton btGenerateKey;
    private javax.swing.JButton btLoadKey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtCiphertext;
    private javax.swing.JTextArea txtPlaintext;
    private javax.swing.JTextField txtPrivateKey;
    private javax.swing.JTextField txtPublicKey;
    // End of variables declaration//GEN-END:variables
}
